[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "FRIDA"
authors = [
    {name = "Kennedy Caisley", email = "kcaisley@uni-bonn.de"},
    {name = "Hans Krüger", email = "krueger@uni-bonn.de"}
]
requires-python = ">= 3.9"
readme = "readme.md"
dependencies = [
    "numpy",
    "matplotlib",
    "pandas",
    "tqdm",
    "cicpy",
    "psf_utils",
]
